### ISSUE TITLE
Specify ClearKey License Release format for persistent-license sessions

### ISSUE THREAD

**Issue by mwatson2** [w3c/encrypted-media#253] opened 2016-06-23 17:35 UTC
Clear Key supports `temporary` and `persistent-usage-record` sessions, but not `persistent-license` sessions.

Since this is an optional capability, it does not have interop implications if added to the specification now.

The only additional material, aside from stating that this session type is supported, is the format for the record of license destruction, which could simply be an object containing the list of key ids.

**Comment by mwatson2** [comment] 2016-06-23 17:36
Do people feel this should be V1NonBlocking or VNext ?

**Comment by ddorwin** [comment] 2016-06-23 18:17
The Clear Key section already says it is supported:
>The "persistent-license" MediaKeySessionType: Implementations may support this type.

Although it is perhaps not explicitly stated, I think the License Release Format and License Release Acknowledgement Format sections may have originally been intended to be used for all session types that fire "license-release" messages. It was probably the addition of "firstTime" and "latestTime" to the License Release Format that makes this less obvious (and technically broken for "persistent-license").

I think this is a bug/regression in the V1 text and should be fixed. Since it doesn't really add anything, I think it's fine.

I suggest that we clarify that this is the format for all "license-release" messages and that the time members are only present for "persistent-release-message" sessions. We can then provide examples for each persistent session type.

**Comment by mwatson2** [comment] 2016-06-24 02:11
PR #256 to specify the Clear Key license release format.

**Closed** 2016-06-24 23:12 UTC
Labels: needs review
