### ISSUE TITLE
Expose CDM version number

### ISSUE THREAD

**Issue by ghost** [w3c/encrypted-media#133] opened 2015-12-03 03:59 UTC
It would be useful to expose the CDM version number on some JS object so that sites that use EME can associate errors they're seeing in the field with a specific version of the CDM.

I propose that we expose the CDM version number as a string on the MediaKeySystemAccess object.

i.e.:

```
partial interface MediaKeySystemAccess {
    readonly        attribute DOMString version;
}

version of type DOMString, readonly
    Identifies the version of the Key System being used.
```

**Comment by mwatson2** [comment] 2016-02-09 00:59
I agree this would be useful for field debugging. Does it introduce additional fingerprinting surface though ? Perhaps that is mitigated by the fact that it can change any time ?

**Comment by paulbrucecotton** [comment] 2016-02-09 17:22
Can other EME implementers besides @ghost such as @jdsmith3000, @ddorwin and @steelejoe please comment on this request?

**Comment by ddorwin** [comment] 2016-02-17 01:42
[I believe `@ghost` is a placeholder for the deleted user `@cpearce-mozilla`. Adding @cpearce to the conversation.]

@mwatson2 wrote:
>I agree this would be useful for field debugging.

Do you mean debugging a client or debugging issues from server logs? There are other ways for user agents to address the former.

</br>I don't believe such things are generally exposed by the web platform (beyond what is in the user agent string). I think we should get broader input on whether/how to handle such things on the web platform, including any concerns about fingerprinting and compatibility concerns (see any modern user agent string for examples of problems that can arise). This also seems similar to the `systemCode` discussion (e.g. [bug 26776 comment 20](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26776#c20) and the earlier bug it references).

The closest comparison is probably the graphics driver version and similar information. There have been discussions about such things in WebGL, with specific beneficial use cases, though I don't know where that ended up. Interestingly, Web MIDI [exposes](https://www.w3.org/TR/webmidi/#widl-MIDIPort-version) "The version of the port."

</br>This is something that would be easy to add in the future and easy for applications to feature detect but difficult to remove once it's added to the spec, so we should be thoughtful in deciding whether and when to expose this. It might be that, for example, including the version in error messages like system codes is sufficient. This seems like a good candidate for incubation.

**Comment by joeyparrish** [comment] 2019-11-19 20:42
I personally don't think exposing a CDM version number would be useful enough to outweigh fingerprinting concerns.  Speaking as an application author working across many desktop, mobile, and CE devices, I find that a UA string is generally enough to identify a client for the purposes of debugging or reproducing errors.  I don't know of any cases where a CDM version is completely independent of the UA, UA version, and OS version information already accessible to me in JavaScript.

If there are other opinions on this, please let me know.  If nobody wants to revive this feature request, I will set a date to close it.

**Comment by joeyparrish** [comment] 2020-07-23 19:09
Since nobody has had any additional comments, I'm going to close the issue.  There doesn't seem to be enough tangible benefit to outweigh the increased fingerprinting surface.

**Closed by joeyparrish** 2020-07-23 19:09 UTC
Labels: feature request

**Comment by estobbart** [comment] 2020-07-23 21:33
Can we reopen? I'd greatly benefit from a browser exposing which version of the spec they support. I've encountered a number of platforms that took a fork of a browser at some point in time when EME was still being drafted. It's very difficult to determine what methods have been implemented, or if arguments are being dropped unknowingly, should I add a listener to _eventType_ or not. For example is scheme read off the the capabilities or is it ignored. A version property might help make those determinations. Open to other ideas if version isn't the answer to this problem described.

**Comment by joeyparrish** [comment] 2020-07-23 22:08
Ah, I see.  What you're describing wouldn't be helped by a _CDM_ version number.  It sounds like what you want is a version number for the _EME_ implementation.  The CDM version doesn't necessarily have anything to do with the capabilities of the EME implementation, or what version of the spec was implemented by the UA.

I'm not aware of other cases where web APIs offer a version number, so I'm not sure how we would do something like that.

As for the specific case you mentioned (encryption scheme capabilities), that was actually addressed in [the proposal for adding that to the spec](https://wicg.github.io/encrypted-media-encryption-scheme/#polyfills).  There is a way you can detect whether or not the `encryptionScheme` field was ignored.  If it's supported, it _must_ appear in the MediaKeySystemMediaCapability object returned from MediaKeySystemAccess.getConfiguration(), even if it's null.  If it's not present in getConfiguration(), it was not implemented by the browser.

This, in turn, creates a basis for building polyfills, such as this one: https://github.com/google/eme-encryption-scheme-polyfill

So instead of detecting whether or not that field has been implemented, you could just install that polyfill and use `encryptionScheme` universally.

Does this help?

**Comment by estobbart** [comment] 2020-07-23 22:41
That's interesting, I wasn't aware of that, thanks! Maybe I picked a bad example though, a better scenario related to this specific request might be what format/version of the initialization data is accepted by the CDM. Specifically for platforms where the CDM might be provided by a SOC vendor, and the browser is provided by a middleware co.

**Comment by joeyparrish** [comment] 2020-07-23 22:59
The init data formats accepted by the CDM can be interrogated through the EME API, and still might vary independent of the CDM version, in cases where such a capability is provided in hardware.  Through `requestMediaKeySystemAccess()`, your app asks for a certain init data format or formats, and the UA can either fulfill the request or reject it if it can't.

**Comment by estobbart** [comment] 2020-07-23 23:10
Maybe let's get specific.. how can I tell which version of a PlayReady [PRO](https://docs.microsoft.com/en-us/playready/specifications/playready-header-specification#31-version-support-matrix) is accepted by the CDM?

**Comment by joeyparrish** [comment] 2020-07-23 23:34
The specifics of PlayReady init data is outside the scope of EME.  That would be a matter for Microsoft, as far as I can tell.  Hopefully, they have given thought to backward compatibility and have some recommendation for how to structure that in a way that degrades gracefully.  (I'm more familiar with the specifics of Widevine, where there is a recommendation of that kind for dealing with older devices that don't understand a newer v1 PSSH format.)

But I take your point.  A PlayReady CDM version number would give you some hope of determining what PRO format it would accept.

But there are still good reasons for the EME standard not to offer a free-form CDM version string, and good alternatives for you as a developer.

Fingerprinting on the web is a big privacy issue already, and this would add some significant amount of information that could be used for fingerprinting.  We've had significant scrutiny over what amounts to a few _bits_ of data in the past, and a CDM version number would be much more than that.  So the benefit would have to be pretty significant to outweigh this as far as I can tell.

And given that there are alternatives for you, it becomes very hard to argue that there is a big enough benefit.

For example, the table you linked to for Microsoft PRO versions shows that all clients back to client SDK v1.x accept header v4.0.0.0.  So one backward compatibility strategy would be to determine if you need to support v1 clients, and if so, use header v4.0.0.0 for all clients.  Or whatever version of the header corresponds to the oldest client you care about.  This may or may not be acceptable for your application, but I'd bet that many apps are already doing this.

Or perhaps you could attempt to use a v4.3.0.0 header format, handle the error, and fall back to an older format.  Or perhaps Microsoft has specific guidance for PlayReady compatibility on the web.

In addition, even if a version number were added, it would only affect future implementations.  Many embedded devices would not receive a UA update to add this field in the first place, effectively making you assume that all existing, non-updating devices could only support the oldest PRO format, v4.0.0.0... which is already an option available to you to achieve compatibility.

**Comment by estobbart** [comment] 2020-07-24 02:31
Understand all the concerns. And the approach you mention works, but it doesn't scale well. It then means the web app needs to be "ported" per platform. Is there another approach that solve both problems? Avoid fingerprinting, no free-form strings, maybe an initData read method that can tell if it's supported without the async bit of processing it? Maybe similar to how codec support is discovered.

**Comment by joeyparrish** [comment] 2020-07-24 18:16
My first suggestion would be to ask Microsoft for official guidance on how they expect PlayReady apps to handle this scenario.  I'm sure you're not the only person with this issue, and I'm sure it's something the PlayReady team has given thought to.

To me, the specifics of PlayReady-specific init data is at the root of this issue, and PlayReady specifics are outside the scope of this spec.  So please reach out to Microsoft for support on this.

If representatives from Microsoft were to say something like "we don't have a solution for this, and the web platform should solve it through version numbers", I would be more inclined to reopen the issue and put effort into a design that mitigates fingerprinting concerns.

But I feel confident that this is something they have already solved for their customers, as Widevine has for its customers.

**Comment by estobbart** [comment] 2020-07-24 21:09
Understand. Thanks. TBH I think it's not just a Microsoft issue... just that they publish their specs and easier to reference the problems. I've seen it with other DRM vendors too.
