### ISSUE TITLE
Disable EME by default in cross-origin iframes 

### ISSUE THREAD

**Issue by raymeskhoury** [w3c/encrypted-media#371] opened 2017-02-08 06:22 UTC
We would like to explore disabling EME by default for cross-origin iframes. The idea is that it would be possible for the embedder to re-enable EME using the proposed [Feature Policy](https://docs.google.com/document/d/1k0Ua-ZWlM_PsFCFdLMa8kaVTo32PeNZ4G7FFHqpFx4E/edit#heading=h.4yubgixv5l6b) mechanism.

Note that this issue is mainly just intended to start the discussion about this change. We still need to nail down the spec for feature policy before this can proceed. I'm also not super familiar with the API so guidance is appreciated :).

EME already has a failure mode that occurs as a result of the user denying permission. This same failure mode can be reused but we probably still want to alter the spec to include the additional check to see if the feature is allowed by Feature Policy.

The motivations for this change and a discussion of compatibility risk can be found here: https://docs.google.com/document/d/13dp9xWVyGM8THAQohDOT2mMOTSGLxEhSZEvgpmVLrxU/edit

@ddorwin @clelland

**Comment by raymeskhoury** [comment] 2017-06-15 04:16
@ddorwin I'd like to look at modifying the spec to add the checks for this. We basically need to call HTMLs "allowed to use" which is monkey-patched by the FP spec (see https://wicg.github.io/feature-policy/#integration-with-html). 

The main question is where to insert the checks. Ideally, wherever we put the FP check would also be the place that user agents have the opportunity to prompt for permission (keeping these 2 things in sync is important in order to keep the permissions story sensible). 

Do you have thoughts on where this should go in the flow? I see that there are currently ways to use requestMediaKeySystemAccess() that don't require a permission grant (at least in Chrome). Should we preserve the ability to do this even when the "encrypted-media" feature isn't enabled? If there are no security/privacy concerns with those invocations then it probably makes sense to continue to allow that.

**Comment by ddorwin** [comment] 2017-06-15 06:43
I think the behavior should be consistent on all implementations, which would mean blocking regardless of whether user consent is required. In that case, we could reject the promise within the first 5 steps of https://w3c.github.io/encrypted-media/#requestMediaKeySystemAccess.

The spec is currently in PR, so we may not be able to make this change in this version, but a pull request would certainly be welcome and could be merged after v1 is complete.

**Comment by ddorwin** [comment] 2017-09-01 18:23
Closing as a duplicate of #364.

**Closed by ddorwin** 2017-09-01 18:23 UTC
