### ISSUE TITLE
Replace "fire a simple event" with "fire an event" for non-simple Events

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#17] opened 2015-01-17 01:59 UTC
We currently link to http://www.w3.org/TR/html5/webappapis.html#fire-a-simple-event, which is incorrect for complex event types. Instead, we should link to http://www.w3.org/TR/html5/infrastructure.html#concept-event-fire like http://www.w3.org/TR/html5/embedded-content-0.html#sourcing-in-band-text-tracks.

Related: We always queue a task to fire the event. Is that necessary?

**Comment by jdsmith3000** [comment] 2015-07-07 01:39
I'd like to reconsider this change.  It recommends replacing "queue a simple event" language with a more detailed explanation for events that are complex (which I interpret to be ones with attributes).  That would appear to change (for example) the current "encrypted" event from:
  -  Queue a task to fire a simple event named encrypted at the media element.
     The event is of type MediaEncryptedEvent and has:
        initDataType = initDataType
        initData = initData
To:
  -  Queue a task to fire a trusted event with the name encrypted, that does not 
      bubble and is not cancelable, that uses the Event interface, and is of type 
      MediaEncryptedEvent with the track attributes initDataType initialized to 
      initDataType and initData initialized to initData, at the media element.

I don't recall a technical reason for making this change, and the current language seems clearer.  The event handling seems identical.

The current EME spec queues 4 "simple events":  Two with no attributes (keystatuseschange & waitingforkey) and two with attributes (message & encrypted).

**Comment by ddorwin** [comment] 2015-07-13 18:04
As discussed in the July 7th telecon, the question is whether "simple event" means exactly "Event" or can include children of Event (with additional members). The answer to this question will determine whether we need to make a change or this issue can be closed as won't fix. @jdsmith3000 will seek clarification on this issue.

**Comment by paulbrucecotton** [comment] 2015-07-28 16:53
Jerry asked the HTML WG for an explanation of "simple event" here:
https://lists.w3.org/Archives/Public/public-html/2015Jul/0022.html

**Comment by jdsmith3000** [comment] 2015-08-01 01:18
I believe I've confirmed that the MediaEncryptedEvent and MediaKeyMessageEvents are not simple events, since they do not directly use the Event interface, but are derived from it.  I'm working to confirm whether David's proposed language is suitable to close this issue.

**Comment by foolip** [comment] 2015-08-05 11:49
If you're doing a lot of firing then you may want to define "fire an encrypted media event", like in https://html.spec.whatwg.org/#fire-a-dnd-event

If it's a one-off you could just create and dispatch the event like in steps 7 and 8 of that algorithm.

(I found this via public-html.)

**Comment by jdsmith3000** [comment] 2015-08-07 23:09
We have custom events defined now - e.g. 
https://w3c.github.io/encrypted-media/#mediakeymessageevent

The discussion was about how best to reference them.  It's not correct to say "fire a simple event", because the definition uses the Event interface.  A simple event is defined as:

Firing a simple event named e means that a trusted event with the name e, which does not bubble (except where otherwise stated) and is not cancelable (except where otherwise stated), and which uses the Event interface, must be created and dispatched at the given target.

I've reviewed this with others, and believe David's original language was essentially correct.  I'd like to modify it slightly to reference the modified event interfaces (MediaKeyMessageEvent & MediaEncryptedEvent), like this:

From: 
Queue a task to fire a simple event named message at the session.

To:
Queue a task to fire a trusted MediaKeyMessageEvent that does not bubble and is not cancelable named message at the session.

Similar language would be used for the MediaEncryptedEvent.

**Comment by foolip** [comment] 2015-08-10 09:08
Per [DOM](https://dom.spec.whatwg.org/#firing-events), "Fire in the context of DOM is short for creating, initializing, and dispatching an event. Fire an event makes that process easier to write down."

In other words, to say "to fire a trusted MediaKeyMessageEvent" would need a separate definition of what it means to do just that, since "to fire" isn't defined in the general case, you need a definition for each shorthand form.

Alternatively, one step to create the event and second to dispatch it would do the same thing.

**Comment by jdsmith3000** [comment] 2015-09-21 22:42
We can address this by including a variation of the DOM spec language for firing events in our revision.  At the DOM link, there is this definition:  
"To fire an event named e means that a new event using the Event interface, with its type attribute initialized to e, and its isTrusted attribute initialized to true, is to be dispatched to the given object."

We could do this in one location, or build it directly into the two events we need to revise.  Eg:  "Queue a task to create an event that does not bubble and is not cancellable using the MediaKeyMessageEvent interface with its type attribute set to message and its isTrusted attribute initialized to true, and dispatch it at the session."

**Comment by ddorwin** [comment] 2015-09-22 20:04
SGTM

Do what makes sense as far as where to define this. Since we have separate algorithms and only two of them, I lean towards being explicit in those algorithms, either in the step(s) or prose.

**Comment by jdsmith3000** [comment] 2015-10-10 02:10
We should go with these two replacements:

"Queue a task to create an event named encrypted that does not bubble and is not cancellable using the MediaEncryptedEvent interface with its type attribute set to message and its isTrusted attribute initialized to true, and dispatch it at the session."

"Queue a task to create an event named message that does not bubble and is not cancellable using the MediaKeyMessageEvent interface with its type attribute set to message and its isTrusted attribute initialized to true, and dispatch it at the session."

I had some trouble with decorating the DOM references and need some input to resolve those.

**Comment by foolip** [comment] 2015-10-16 18:55
Looks reasonable, but note the type "type attribute set to message" in the first case.

**Comment by jdsmith3000** [comment] 2015-10-28 07:15
This is ready for editing.

**Comment by jdsmith3000** [comment] 2016-02-02 17:57
Fix checked in 12 days ago.  Issue should be closed.

**Closed by jdsmith3000** 2016-02-02 17:57 UTC
Labels: needs implementation
